### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by Wulf** [Wulf/nodehun#35]
- [x] Add TravisCI for Linux and OSX builds
- [x] Add AppVeyor for Windows builds

**Comment by Wulf** [comment]
For some reason, the builds are failing.
[WIP](/wulf/nodehun/#35-ci)

**Comment by Thomas101** [comment]
I don't know if this will help, in my fork I've configured [travis](https://github.com/Thomas101/nodehun/blob/master/.travis.yml) and [appveyor](https://github.com/Thomas101/nodehun/blob/master/appveyor.yml) to generate precompiled binaries for my own project. Would be happy to share some experience if you need any help on this.

**Comment by Wulf** [comment]
Thanks Thomas! I'll look to your examples.

**Comment by Wulf** [comment]
For future reference: 
Travis-CI doesn't provide a 32-bit testing environment according to [this issue](https://github.com/travis-ci/travis-ci/issues/986).

@Thomas101 I think I got it working! Would you mind looking over the [.travis.yml](https://github.com/Wulf/nodehun/blob/feature/%2335-ci/.travis.yml) and [appveyor.yml](https://github.com/Wulf/nodehun/blob/feature/%2335-ci/appveyor.yml) files?

**Comment by Thomas101** [comment]
That looks about right (I'm no expert on this -- I've just been trial and error). You can get travis to do 32bit builds on a 64bit box. You basically have to install the 32bit version and compilers. It's a bit messy but there's quite a few repos out there using it. Here's how I managed it...

[Full Reference](https://github.com/Thomas101/nodehun/blob/master/.travis.yml)

```yml
# Set your node versions through environment vars and also set your arch
env:
  - TRAVIS_NODE_VERSION="6.3.0"
  - TRAVIS_NODE_VERSION="6.3.0" ARCH="x86"

# Tell osx not to build 32bit versions (note the env has to match exactly)
matrix:
  exclude:
    - os: osx
      env: TRAVIS_NODE_VERSION="6.3.0" ARCH="x86"

# Setup gcc for 64bit builds in the usual way
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib

# Setup node & GCC for the arch and platform
before_install:

# Use correct node version (x64)
  - nvm install $TRAVIS_NODE_VERSION

# Check if we're x86 then wget node, install it, export it as the default node
  - PATH=$PATH:`pwd`/node_modules/.bin
  - BASE_URL=$(node -p "'https://nodejs.org/download/release/' + process.version")
  - X86_FILE=$(node -p "'node-' + process.version + '-' + process.platform + '-x86'")
  - if [[ "$ARCH" == "x86" ]]; then wget $BASE_URL/$X86_FILE.tar.gz; tar -xf $X86_FILE.tar.gz; export PATH=$X86_FILE/bin:$PATH; fi

# Check if we're x86 then install the i386 gcc and g++ and export that as the default. Note this ends in a dependency problem warning which causes travis to bork hence adding the | true to the end
  - if [[ "$ARCH" == "x86" ]]; then sudo apt-get -y install binutils:i386 gcc-4.8:i386 g++-4.8:i386 | true; fi
  - export CXX=g++-4.8;

# Do your stuff!
script:
  - npm install -g node-gyp
  - node-gyp rebuild
  - npm test
```
